database:
  host: 127.0.0.1
  port: 5432
  user: user
  password: password
  dbname: mydatabase
  sslmode: disable

log_level: debug

storage:
  kind: s3
  s3:
    bucket: my-bucket
    prefix: my-prefix
    region: us-west-2
    endpoint: http://localhost:9000
    use_path_style: true
    access_key: myaccesskey
    secret_key: mysecretkey
