// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Package struct {
	Name           string
	Summary        pgtype.Text
	LatestVersion  pgtype.Text
	CreatedAt      pgtype.Timestamptz
	LastUploadedAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Release struct {
	Version                string
	PackageName            pgtype.Text
	Summary                pgtype.Text
	Description            pgtype.Text
	DescriptionContentType pgtype.Text
	FileName               pgtype.Text
	FileType               pgtype.Text
	Pyversion              pgtype.Text
	RequiresPython         pgtype.Text
	RequiresDist           []string
	Md5Digest              pgtype.Text
	Sha256Digest           pgtype.Text
	Blake2256Digest        pgtype.Text
	CreatedAt              pgtype.Timestamptz
	Yanked                 pgtype.Bool
	YankedReason           pgtype.Text
	YankedAt               pgtype.Timestamptz
}
